In [1]:
import tensorflow as tf
tf.__version__

'1.5.0'

tf.constant

In [2]:
hello = tf.constant("Hello, TensorFlow!")
a = tf.constant(10)

print(hello)
print(a)

Tensor("Const:0", shape=(), dtype=string)
Tensor("Const_1:0", shape=(), dtype=int32)


tf.Variable

In [4]:
W = tf.Variable(tf.random_normal([3,2]))
b = tf.Variable(tf.random_normal([2,1]))

print(W)
print(b)

<tf.Variable 'Variable_2:0' shape=(3, 2) dtype=float32_ref>
<tf.Variable 'Variable_3:0' shape=(2, 1) dtype=float32_ref>


tf.placeholder

In [5]:
node1 = tf.placeholder(tf.float32)
node2 = tf.placeholder(tf.float32)

node3 = node1 + node2

sess = tf.Session()

print(sess.run(node3))

InvalidArgumentError: You must feed a value for placeholder tensor 'Placeholder_1' with dtype float
	 [[Node: Placeholder_1 = Placeholder[dtype=DT_FLOAT, shape=<unknown>, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

Caused by op 'Placeholder_1', defined at:
  File "d:\app\anaconda3\envs\tf15\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "d:\app\anaconda3\envs\tf15\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "d:\app\anaconda3\envs\tf15\lib\site-packages\ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "d:\app\anaconda3\envs\tf15\lib\site-packages\traitlets\config\application.py", line 658, in launch_instance
    app.start()
  File "d:\app\anaconda3\envs\tf15\lib\site-packages\ipykernel\kernelapp.py", line 486, in start
    self.io_loop.start()
  File "d:\app\anaconda3\envs\tf15\lib\site-packages\tornado\platform\asyncio.py", line 132, in start
    self.asyncio_loop.run_forever()
  File "d:\app\anaconda3\envs\tf15\lib\asyncio\base_events.py", line 422, in run_forever
    self._run_once()
  File "d:\app\anaconda3\envs\tf15\lib\asyncio\base_events.py", line 1434, in _run_once
    handle._run()
  File "d:\app\anaconda3\envs\tf15\lib\asyncio\events.py", line 145, in _run
    self._callback(*self._args)
  File "d:\app\anaconda3\envs\tf15\lib\site-packages\tornado\platform\asyncio.py", line 122, in _handle_events
    handler_func(fileobj, events)
  File "d:\app\anaconda3\envs\tf15\lib\site-packages\tornado\stack_context.py", line 300, in null_wrapper
    return fn(*args, **kwargs)
  File "d:\app\anaconda3\envs\tf15\lib\site-packages\zmq\eventloop\zmqstream.py", line 450, in _handle_events
    self._handle_recv()
  File "d:\app\anaconda3\envs\tf15\lib\site-packages\zmq\eventloop\zmqstream.py", line 480, in _handle_recv
    self._run_callback(callback, msg)
  File "d:\app\anaconda3\envs\tf15\lib\site-packages\zmq\eventloop\zmqstream.py", line 432, in _run_callback
    callback(*args, **kwargs)
  File "d:\app\anaconda3\envs\tf15\lib\site-packages\tornado\stack_context.py", line 300, in null_wrapper
    return fn(*args, **kwargs)
  File "d:\app\anaconda3\envs\tf15\lib\site-packages\ipykernel\kernelbase.py", line 283, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "d:\app\anaconda3\envs\tf15\lib\site-packages\ipykernel\kernelbase.py", line 233, in dispatch_shell
    handler(stream, idents, msg)
  File "d:\app\anaconda3\envs\tf15\lib\site-packages\ipykernel\kernelbase.py", line 399, in execute_request
    user_expressions, allow_stdin)
  File "d:\app\anaconda3\envs\tf15\lib\site-packages\ipykernel\ipkernel.py", line 208, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "d:\app\anaconda3\envs\tf15\lib\site-packages\ipykernel\zmqshell.py", line 537, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "d:\app\anaconda3\envs\tf15\lib\site-packages\IPython\core\interactiveshell.py", line 2662, in run_cell
    raw_cell, store_history, silent, shell_futures)
  File "d:\app\anaconda3\envs\tf15\lib\site-packages\IPython\core\interactiveshell.py", line 2785, in _run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "d:\app\anaconda3\envs\tf15\lib\site-packages\IPython\core\interactiveshell.py", line 2901, in run_ast_nodes
    if self.run_code(code, result):
  File "d:\app\anaconda3\envs\tf15\lib\site-packages\IPython\core\interactiveshell.py", line 2961, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-5-b907f244d9dc>", line 2, in <module>
    node2 = tf.placeholder(tf.float32)
  File "d:\app\anaconda3\envs\tf15\lib\site-packages\tensorflow\python\ops\array_ops.py", line 1680, in placeholder
    return gen_array_ops._placeholder(dtype=dtype, shape=shape, name=name)
  File "d:\app\anaconda3\envs\tf15\lib\site-packages\tensorflow\python\ops\gen_array_ops.py", line 4105, in _placeholder
    "Placeholder", dtype=dtype, shape=shape, name=name)
  File "d:\app\anaconda3\envs\tf15\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "d:\app\anaconda3\envs\tf15\lib\site-packages\tensorflow\python\framework\ops.py", line 3160, in create_op
    op_def=op_def)
  File "d:\app\anaconda3\envs\tf15\lib\site-packages\tensorflow\python\framework\ops.py", line 1625, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): You must feed a value for placeholder tensor 'Placeholder_1' with dtype float
	 [[Node: Placeholder_1 = Placeholder[dtype=DT_FLOAT, shape=<unknown>, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]


In [6]:
print(sess.run(node3, feed_dict={node1: 3., node2: 4.}))
print(sess.run(node3, feed_dict={node1: [3,5], node2: [4,6]}))

7.0
[ 7. 11.]


reduce_sum

In [24]:
import numpy as np

# list
x = [[1., 2., 3.], [4., 5., 6.]]

sess = tf.Session()

x = np.array(x)

print("x: ", x)
print("x.shape: ", x.shape)

print("reduce_sum: ", sess.run(tf.reduce_sum(x)))
print("reduce_sum.shape: ", sess.run(tf.reduce_sum(x)).shape)


x:  [[1. 2. 3.]
 [4. 5. 6.]]
x.shape:  (2, 3)
reduce_sum:  21.0
reduce_sum.shape:  ()


reduce_mean

In [25]:
print("reduce_mean: ", sess.run(tf.reduce_mean(x)))
print("reduce_mean.shape: ", sess.run(tf.reduce_mean(x)).shape)

print("reduce_mean(axis=0): ", sess.run(tf.reduce_mean(x, axis=0)))
print("reduce_mean(axis=0).shape: ", sess.run(tf.reduce_mean(x, axis=0)).shape)

print("reduce_mean(axis=1): ", sess.run(tf.reduce_mean(x, axis=1)))
print("reduce_mean(axis=1).shape: ", sess.run(tf.reduce_mean(x, axis=1)).shape)


reduce_mean:  3.5
reduce_mean.shape:  ()
reduce_mean(axis=0):  [2.5 3.5 4.5]
reduce_mean(axis=0).shape:  (3,)
reduce_mean(axis=1):  [2. 5.]
reduce_mean(axis=1).shape:  (2,)


tf.matmul

In [27]:
X = [[1., 2., 3.], [1., 2., 3.]]
W = [[1.], [1.], [1.]]

# 2x3  *  3x1  =>  2x1 matrix
print("X*W: \n", sess.run(tf.matmul(X, W)))

X*W: 
 [[6.]
 [6.]]


tf.cast

In [28]:
x = tf.constant([1.2, 3.1], dtype=tf.float32)
print(x)
print(sess.run(x))

x = tf.cast(x, tf.int32)
print(x)
print(sess.run(x))


Tensor("Const_2:0", shape=(2,), dtype=float32)
[1.2 3.1]
Tensor("Cast:0", shape=(2,), dtype=int32)
[1 3]


tf.stack

In [33]:
x = tf.constant([1, 4])
y = tf.constant([2, 5])
z = tf.constant([3, 6])

print(sess.run(tf.stack([x,y,z])))
print(sess.run(tf.stack([x,y,z], axis=1)))

[[1 4]
 [2 5]
 [3 6]]
[[1 2 3]
 [4 5 6]]
